version: "2.4"
#-------------------------------- volumes----------------------------------------
volumes:
  db:
  #--------------------------------services----------------------------------------
services:
  kaddem:
    image: sarraharguem/kaddemproject:v5
    restart: always
    depends_on:
      - mysql
    ports:
      - 8089:8089
    environment:
      - spring.datasource.url=jdbc:mysql://mysqlkaddem:3306/kaddem?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    #-------------------------------- database ----------------------------------------

  mysqlkaddem:
    container_name: mysqlkaddem
    image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: kaddem
      MYSQL_ROOT_PASSWORD: root