version: "2.4"
#-------------------------------- volumes----------------------------------------
volumes:
  db:
  #--------------------------------services----------------------------------------
services:
  khaddemservice:
    image: dorra22/springkhaddem:v3
    restart: always
    depends_on:
      - mysqlkhaddem
    ports:
      - 8089:8089
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqlkhaddem:3306/khaddem?createDatabaseIfNotExist=true&userSSL=false&max_allowed_packet=15728640
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=dorra
    #-------------------------------- database ----------------------------------------

  mysqlkhaddem:
    container_name: mysqlkhaddem
    image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: khaddem
      MYSQL_ROOT_PASSWORD: dorra

  mysql-exporter:
    image: prom/mysqld-exporter
    environment:
      - DATA_SOURCE_NAME=root:dorra@(mysqlkhaddem:3306)/
    ports:
      - "9104:9104"


