version: "2.4"
#-------------------------------- volumes----------------------------------------
volumes:
  db:

  #--------------------------------services----------------------------------------
services:

  khaddemservice:
    image: dorra22/springkhaddem:v3
    restart: always
    depends_on:
      - mysqlkhaddem
    ports:
      - 8089:8089
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqlkhaddem:3306/khaddem?createDatabaseIfNotExist=true&userSSL=false&max_allowed_packet=15728640
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=dorra

    #-------------------------------- database ----------------------------------------

  mysqlkhaddem:
    container_name: mysqlkhaddem
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: khaddem
      MYSQL_ROOT_PASSWORD: dorra

  mysql-exporter:
    image: quay.io/prometheus/mysqld-exporter
    container_name: mysql-exporter
    restart: unless-stopped
    ports:
      - 9104:9104
    command:
      - "--mysqld.username=root:dorra"
      - "--mysqld.address=mysqlkhaddem:3306"
    environment:
      - DATA_SOURCE_NAME='root:dorra@tcp(mysqlkhaddem:3306)/khaddem'
      - collect.info_schema.tablestats=true
      - collect.info_schema.userstats=true
      - collect.info_schema.query_response_time=true
      - collect.auto_increment.columns=true
      - collect.binlog_size=true
      - collect.perf_schema.eventsstatements=true
      - collect.perf_schema.eventswaits=true
      - collect.perf_schema.file_events=true
      - collect.perf_schema.indexiowaits=true
      - collect.perf_schema.tableiowaits=true
      - collect.perf_schema.tablelocks=true
    depends_on:
      - mysqlkhaddem

