version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: kaddem
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network1
  spring:
    image: oumaymahajri572/oumaymahajri-5twin4-g2-kaddem:v1
    restart: always
    ports:
      - "8089:8089"
    environment:
        - spring.datasource.url=jdbc:mysql://mysqlkaddem:3306/kaddem?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db
    stdin_open: true
    tty: true
    networks:
      - network1

volumes:
  db_data: {}
networks:
  network1:
    driver: bridge