version: "2.4"
#-------------------------------- volumes----------------------------------------
volumes:
  db:
  #--------------------------------services----------------------------------------
services:
  khaddemservice:
    image: dorra22/springkhaddem
    restart: always
    depends_on:
      - mysqlkhaddem
    ports:
      - 8089:8089
    environment:
      MYSQL_HOST: mysqlkhaddem
      MYSQL_USER: root
      MYSQL_PASSWORD: dorra

    #-------------------------------- database ----------------------------------------

  mysqlkhaddem:
    container_name: mysqlkhaddem
    image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: khaddem
      MYSQL_ROOT_PASSWORD: dorra




