version: "3.8"

networks:

  backendNetwork:  # Define another custom network
    driver: bridge

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: kaddem
    volumes:
      - db:/var/lib/mysql
    networks:
      - backendNetwork

  kaddem-backend:
    image: oumaymahajri572/oumaymahajri-5twin4-g2-kaddem:v1
    restart: unless-stopped
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    networks:
      - backendNetwork   # Attach to the custom network


volumes:
  db:  # Volume for mysqldb
