version: "3.8"
services:
  dbkaddem:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: kaddem
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  spring:
    image: oumaymahajri572/oumaymahajri-5twin4-g2-kaddem:v1
    restart: always
    ports:
      - 8089:8089
    environment:
        - spring.datasource.url=jdbc:mysql://dbkaddem:3306/kaddem?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - dbkaddem


volumes:
  db_data:
