version: "2.4"
services:
  khaddemservice:
    image: dorra22/springkhaddem:v3
    restart: always
    depends_on:
      - mysqlkhaddem
    ports:
      - 8089:8089
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqlkhaddem:3306/khaddem?createDatabaseIfNotExist=true&useSSL=false&max_allowed_packet=15728640
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=dorra
    networks:
      - mynetwork

  mysqlkhaddem:
    container_name: mysqlkhaddem
    image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: khaddem
      MYSQL_ROOT_PASSWORD: dorra
    networks:
      - mynetwork

  mysql-exporter:
    image: prom/mysqld-exporter
    restart: always
    ports:
      - 9104:9104
    environment:
      DATA_SOURCE_NAME: root:dorra@(mysqlkhaddem:3306)/khaddem
    networks:
      - mynetwork


networks:
  mynetwork:
